server:
  port: 8090

spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2


# gRPC 서버 설정
grpc:
  server:
    port: 50051
  client:
    chat-server:  # 클라이언트가 참조할 서비스 이름
      address: "static://localhost:50051"  # gRPC 서버 주소
      negotiationType: plaintext  # TLS를 사용하지 않으므로 평문 통신 설정
